### ISSUE TITLE
frontend-app-library-authoring Initial Maintenance

### ISSUE THREAD

**Issue by feanil** [openedx/frontend-app-library-authoring#107]
- [x] Github Issues is Enabled
- [x] A `catalog-info.yaml` file exists
- [x] Dependency Update Automation is Enabled
- [x] A well-formed README exists.

[Details and links to how-tos.](https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html)

**Comment by jristau1984** [comment]
While the readme is not perfect, I believe that it is good enough for the expectations of this ticket considering that this repo is not fully stable yet.
