### ISSUE TITLE
there's no tutor-contrib-library-authoring-mfe!

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/frontend-app-library-authoring#305]
I was reading the docs and noticed `tutor-contrib-library-authoring-mfe` is mentioned but the link returns 404. Is it private or something you're working on for the future?

**Comment by jesperhodge** [comment]
Hi @CodeWithEmad , it seems like the `tutor-contrib-library-authoring-mfe` was moved out of this repository. The commit message just gave "elsewhere" as destination xD so I had a look in the openedx org, and found it [here](https://github.com/openedx/openedx-tutor-plugins/tree/main/plugins/tutor-contrib-library-authoring-mfe).

I'll update the link in the docs, thanks for pointing this out! Hope I could help.

**Comment by CodeTherapy-ir** [comment]
Awesome! Thanks.

**Comment by CodeWithEmad** [comment]
Awesome! Thanks.
