### ISSUE TITLE
Hide Import option from Library Header

### ISSUE THREAD

**Issue by connorhaugh** [openedx/frontend-app-library-authoring#415]
Importing content into a library has not been fully built out as a feature yet. We plan to add it later, after it has been built out. Let’s remove the page from the header for now, and we can add it back later when the feature is done. Technical details: This is a “remove one line“ ticket.

**Comment by imasdekar** [comment]
@connorhaugh @navinkarkera  I am trying to work on this issue. Is the import option to be removed the one in the below screenshot(under the settings menu)?

![image](https://github.com/openedx/frontend-app-library-authoring/assets/29521808/8f150541-197d-4658-a021-7f2401320d54)



But upon visiting the import option(under settings) I am able to import the courses. Please refer to the screenshot below.


![image](https://github.com/openedx/frontend-app-library-authoring/assets/29521808/e0bce90a-54b4-4d95-8643-23e0dbb62e85)

**Comment by navinkarkera** [comment]
@connorhaugh Gentle reminder

**Comment by kdmccormick** [comment]
Closing [as this repo has been deprecated](https://github.com/openedx/frontend-app-library-authoring/issues/439). We'll keep an eye on this in the frontend-app-course-authoring reimplementation of the feature.
