### ISSUE TITLE
Use a shared header component, instead of a custom one.

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/frontend-app-library-authoring#70]
Pick up where https://github.com/openedx/frontend-app-library-authoring/pull/36 left off and refactor the frontend-app-library-authoring header to use frontend-component-header in such a way that is also usable by frontend-app-course-authoring (currently the only other Studio-like MFE).

**Comment by arbrandes** [comment]
@brian-smith-tcril, can you please assign yourself?

**Comment by brian-smith-tcril** [comment]
@arbrandes looks like i don't have perms to assign myself

**Comment by arbrandes** [comment]
Hmm, but now that you commented, I was able to assign it to you.  (GH project woes. 🙄)
