### ISSUE TITLE
CSS refactor

### ISSUE THREAD

**Issue by Carlos-Muniz** [openedx/frontend-app-library-authoring#72]
We were probably the last ones to use the old edx theme from Paragon (which helped us achieve the Studio look faster), but it's now gone, leaving many boxes and buttons unstyled.  Refactor the styling so that it no longer uses the included `vendor` CSS, instead relying as much as possible on Paragon.

#### Acceptance criteria

* [x] No page relies on `vendor/studio.scss`, `vendor/normalize.scss` or `vendor/overrides.scss`, but the general page layout is preserved.  (For instance, buttons should be where existing users expect them to be.)
* [x] Styling of individual page elements need not be preserved, but elements should be converted to their closest Paragon equivalents.
* [x] If no Paragon component exists to replace legacy code, a new one should be create locally with a mind to eventually contribute it as a new one (or an update to an existing one).
* [x] `src/vendor` is completely removed

**Comment by arbrandes** [comment]
@brian-smith-tcril, I've listed some acceptance criteria for us to discuss.  The idea is for you to tackle this following the merge of https://github.com/openedx/frontend-app-library-authoring/issues/70.
