### ISSUE TITLE
Remove disallowed generic PropTypes workarounds

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-library-authoring#81]
On the Course Import page we're forcing the use of generic object PropType via an ugly `PropTypes.objectOf(PropTypes.object)`.  See here:

https://github.com/openedx/frontend-app-library-authoring/blob/f62d0aa/src/library-authoring/course-import/CourseImportPage.jsx#L151

Remove that and alter the `ongoingImport` data structure accordingly so we can use a definite PropType.

**Comment by jristau1984** [comment]
This has been brought into the 2U Library Authoring epic with this internal ticket: https://2u-internal.atlassian.net/browse/TNL-10592

**Comment by navinkarkera** [comment]
@jristau1984 @arbrandes Is this issue still relevant?

**Comment by arbrandes** [comment]
Yes, the hack is still there:

https://github.com/openedx/frontend-app-library-authoring/blob/f62d0aa/src/library-authoring/course-import/CourseImportPage.jsx#L151

**Comment by kdmccormick** [comment]
Closing per https://github.com/openedx/frontend-app-library-authoring/issues/439
