### ISSUE TITLE
Use `Form.Autosuggest` for `OrganizationDropdown`

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-app-library-authoring#82]
The dropdown is having some z-order issues at the moment, instead of trying to address those in css it probably makes more sense to just replace it with a paragon autosuggest https://paragon-openedx.netlify.app/components/form/form-autosuggest/

**Comment by arbrandes** [comment]
See related Slack thread [here](https://openedx.slack.com/archives/CH298889G/p1666977852997829).

**Comment by brian-smith-tcril** [comment]
also see [this issue](https://github.com/openedx/paragon/issues/1732) on the paragon repo

**Comment by brian-smith-tcril** [comment]
I think this can be closed as https://github.com/openedx/frontend-app-library-authoring/pull/269 replaced the `OrganizationDropdown` with a `TypeaheadDropdown` from `frontend-lib-content-components`
