### ISSUE TITLE
UI Idea/Suggestion: add block type to listing in library

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-app-library-authoring#87]
We currently only show the title of each block in the libraries. I was thinking it might be nice to also display the block type as a subheading of some sort.

**Comment by jristau1984** [comment]
@cablaa77 please review this enhancement request.

**Comment by navinkarkera** [comment]
@brian-smith-tcril If I am not wrong, this has been resolved by https://github.com/openedx/frontend-app-library-authoring/pull/74. Can we close this issue?

**Comment by brian-smith-tcril** [comment]
@navinkarkera  https://github.com/openedx/frontend-app-library-authoring/pull/74 just removed the `StudioHeader` component and replaced it with the header from `frontend-component-header`. I don't believe it touched anything related to the block listings.

**Comment by kdmccormick** [comment]
The [overhauled library listing page](https://www.figma.com/design/Y3gSyrpG6uncUUfjK7eQuo/Content-Libraries-and-Taxonomies?node-id=1459-34065&t=rMrRTfM2WUlQaM76-0), which'll be implemented in frontend-app-course-authoring, will include this change.
