### ISSUE TITLE
organization names in the org dropdown only use shortnames

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-app-library-authoring#88]
the `/organizations` endpoint used to populate the organizations dropdown (on the create library page) is only returning shortnames, it'd be nice to update this to allow for user friendly names in the dropdown

**Comment by jristau1984** [comment]
@cablaa77 please review this enhancement request.

**Comment by navinkarkera** [comment]
@brian-smith-tcril @jristau1984 Is this issue still relevant?

**Comment by brian-smith-tcril** [comment]
I believe this is still the case, but it is likely an enhancement request that requires product evaluation.

**Comment by kdmccormick** [comment]
I'll keep on eye on the [frontend-app-course-authoring reimpl ](https://github.com/openedx/frontend-app-course-authoring/blob/master/src/library-authoring/create-library/CreateLibrary.tsx) to make sure this is fixed.
