### ISSUE TITLE
Loss of field focus after each character for search field

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-library-authoring#90]
Gradebook has the same problem.  See https://github.com/openedx/frontend-app-gradebook/pull/262 for the description and the fix.

**Comment by jristau1984** [comment]
This issue has been brought into the 2U Library Authoring epic thru internal ticket: https://2u-internal.atlassian.net/browse/TNL-10594

**Comment by navinkarkera** [comment]
@jristau1984 @arbrandes Is this issue still relevant?

**Comment by arbrandes** [comment]
I haven't tested this in a long time.  If  you can´t reproduce it in master, it's safe to close it.

**Comment by navinkarkera** [comment]
@arbrandes It seems to be fixed with newer versions of paragon. I cannot reproduce it now.
